server {
  listen 80;
  location = /health { return 200 'UP'; add_header Content-Type text/plain; }
  location / { proxy_pass http://frontend; }
  location /api/ { proxy_pass http://backend:8080; }
}
