CREATE TABLE paper_trade_journal (
    id UUID PRIMARY KEY,
    account_id UUID NOT NULL REFERENCES paper_accounts(id),
    trade_id UUID,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    trade_type VARCHAR(16) NOT NULL,
    symbol VARCHAR(80) NOT NULL,
    option_symbol VARCHAR(120),
    option_type VARCHAR(8),
    strike VARCHAR(32),
    expiry VARCHAR(16),
    direction VARCHAR(16),
    nifty_entry_level NUMERIC(20,6),
    nifty_exit_level NUMERIC(20,6),
    expected_move_points NUMERIC(20,6),
    expected_target NUMERIC(20,6),
    horizon_minutes INTEGER,
    confidence NUMERIC(10,6),
    scenario_validity VARCHAR(32),
    entry_price NUMERIC(20,6),
    exit_price NUMERIC(20,6),
    quantity INTEGER,
    lot_size INTEGER,
    gross_pnl NUMERIC(20,6),
    charges NUMERIC(20,6),
    slippage NUMERIC(20,6),
    net_pnl NUMERIC(20,6),
    entry_time TIMESTAMP WITH TIME ZONE,
    exit_time TIMESTAMP WITH TIME ZONE,
    holding_minutes BIGINT,
    exit_reason VARCHAR(128),
    risk_decision VARCHAR(32),
    risk_rejection_reasons TEXT,
    model_version VARCHAR(64),
    market_regime VARCHAR(64),
    volatility_regime VARCHAR(64),
    decision_reason TEXT,
    status VARCHAR(16)
);

CREATE INDEX idx_journal_account_time ON paper_trade_journal(account_id, timestamp DESC);
CREATE INDEX idx_journal_type_time ON paper_trade_journal(trade_type, timestamp DESC);
