package com.tradingplatform.paper;
import com.tradingplatform.market.websocket.MarketTick; import com.tradingplatform.persistence.*; import java.math.BigDecimal; import java.time.Instant; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.transaction.annotation.Transactional; import static org.junit.jupiter.api.Assertions.*;
@SpringBootTest(properties={"trading.paper.initial-balance=1000","trading.paper.max-allocation-per-trade=1000","trading.paper.charges.brokerage-rate=0"}) class PaperTradingEngineIntegrationTest {
 @Autowired PaperTradingEngine engine; @Autowired PaperTickListener ticks; @Autowired InstrumentCatalogRepository instruments; @Autowired PaperAccountRepository accounts; @Autowired PaperPositionRepository positions; @Autowired PaperOrderRepository orders;
 @BeforeEach void setup(){orders.deleteAll();positions.deleteAll();accounts.deleteAll();instruments.deleteAll();InstrumentEntity i=new InstrumentEntity();i.instrumentKey="MOCK|TEST";i.exchange="NSE";i.segment="NSE_EQ";i.symbol="TEST";i.instrumentType="EQ";i.tradingSymbol="TEST";i.active=true;i.lastUpdated=Instant.now();instruments.save(i);}
 private void tick(String value){ticks.accept(new MarketTick("MOCK|TEST",Instant.now(),new BigDecimal(value),BigDecimal.ONE,BigDecimal.TEN,new BigDecimal(value),new BigDecimal(value),new BigDecimal(value),new BigDecimal(value)));}
 @Test void buyTickTargetExitUpdatesAuthoritativePnl(){tick("7.50");var buy=engine.submit(new PaperDtos.OrderRequest("TEST",PaperSide.BUY,10,null,new BigDecimal("8.00")));assertEquals(PaperOrderStatus.FILLED,buy.status());assertEquals(1,engine.positions().size());tick("8.00");assertTrue(engine.positions().isEmpty());assertEquals(2,engine.orders().size());assertEquals(new BigDecimal("5.00"),engine.account().realizedPnl());}
 @Test void staleOrMissingPriceRejectsWithoutPosition(){var rejected=engine.submit(new PaperDtos.OrderRequest("TEST",PaperSide.BUY,1,null,null));assertEquals(PaperOrderStatus.REJECTED,rejected.status());assertTrue(engine.positions().isEmpty());}
 @Test void stopLossClosesLongPosition(){tick("10.00");assertEquals(PaperOrderStatus.FILLED,engine.submit(new PaperDtos.OrderRequest("TEST",PaperSide.BUY,5,new BigDecimal("9.00"),null)).status());tick("9.00");assertTrue(engine.positions().isEmpty());assertEquals(new BigDecimal("-5.00"),engine.account().realizedPnl());}
}
