import { useEffect, useState } from 'react';
import { api, type ModelStatus, type Quote, type ScannerResult } from '../services/api';

const money = (value?: number | null) => value == null ? '—' : new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(value);

export function LiveDashboard({ open }: { open: (view: 'Instrument' | 'Strategies' | 'ML Lab') => void }) {
  const [quote, setQuote] = useState<Quote>(); const [signals, setSignals] = useState<ScannerResult[]>([]); const [model, setModel] = useState<ModelStatus>(); const [error, setError] = useState('');
  useEffect(() => { let live = true; const load = async () => { try { const [q, scan, status] = await Promise.all([api.quote('NIFTY'), api.scanner('1D'), api.modelStatus()]); if (live) { setQuote(q); setSignals(scan.results); setModel(status); setError(''); } } catch { if (live) setError('Live market data is unavailable. Check the backend and market-data provider.'); } }; void load(); const timer = window.setInterval(() => void load(), 15000); return () => { live = false; window.clearInterval(timer); }; }, []);
  return <main><div className="heading"><div><small>LIVE BACKEND DATA</small><h1>Market dashboard</h1><p>Quotes, scanner signals, and model status refresh from the trading backend.</p></div><button className="primary" onClick={() => open('Strategies')}>Open scanner →</button></div>{error && <p className="api-state error">{error}</p>}<section className="stats"><Metric label="NIFTY 50" value={quote ? quote.price.toFixed(2) : 'Loading…'} hint={quote ? `${quote.changePercent >= 0 ? '+' : ''}${quote.changePercent.toFixed(2)}% today` : 'Waiting for quote'} good={Boolean(quote && quote.changePercent >= 0)} /><Metric label="Live volume" value={quote ? new Intl.NumberFormat('en-IN', { notation: 'compact' }).format(quote.volume) : '—'} hint="Latest quote volume" /><Metric label="Scanner results" value={String(signals.length)} hint="Current backend scan" /><Metric label="ML model" value={model?.status ?? 'UNTRAINED'} hint={model?.modelVersion ?? 'Train a model to enable predictions'} good={model?.status === 'READY'} /></section><div className="two"><section className="panel market"><div className="panel-title"><div><small>LIVE QUOTE</small><h2>NIFTY 50</h2></div><span className={`pill ${quote && quote.changePercent >= 0 ? 'up' : 'sell'}`}>{quote ? quote.timestamp : 'CONNECTING'}</span></div>{quote ? <div className="quote-grid"><b>{money(quote.price)}</b><span className={quote.changePercent >= 0 ? 'good' : 'bad'}>{quote.change >= 0 ? '+' : ''}{quote.change.toFixed(2)} ({quote.changePercent.toFixed(2)}%)</span><small>Open {money(quote.open)} · H {money(quote.high)} · L {money(quote.low)}</small></div> : <Loading label="Requesting NIFTY quote…" />}</section><section className="panel"><div className="panel-title"><div><small>MODEL STATUS</small><h2>Prediction service</h2></div><button onClick={() => open('ML Lab')}>ML analytics →</button></div>{model ? <div className="model-facts"><span>Version <b>{model.modelVersion ?? '—'}</b></span><span>Validation accuracy <b>{model.accuracy == null ? '—' : `${(model.accuracy * 100).toFixed(1)}%`}</b></span><span>Macro F1 <b>{model.f1Macro ?? '—'}</b></span><span>Training rows <b>{model.trainingRows ?? '—'}</b></span></div> : <Loading label="Loading model status…" />}</section></div><section className="panel backend-table"><div className="panel-title"><div><small>BACKEND STRATEGY SCAN</small><h2>Actionable signals</h2></div><button onClick={() => open('Instrument')}>Instrument analysis →</button></div>{signals.length === 0 ? <Loading label="No scanner results returned yet." /> : signals.slice(0, 6).map(signal => <button className="api-row" key={signal.symbol} onClick={() => open('Instrument')}><b>{signal.symbol}</b><span className={`pill ${signal.signal.toLowerCase()}`}>{signal.signal}</span><span>Score <b>{signal.signalStrength}</b></span><span>{money(signal.price)}</span><small>{signal.reasons?.[0] ?? 'No strategy reason supplied.'}</small></button>)}</section></main>;
}
function Metric({ label, value, hint, good }: { label: string; value: string; hint: string; good?: boolean }) { return <div className="card"><span>{label}</span><b>{value}</b><small className={good ? 'good' : ''}>{hint}</small></div>; }
export function Loading({ label }: { label: string }) { return <p className="api-state">{label}</p>; }
