package com.tradingplatform.market;

import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import java.time.Duration; import java.util.*; import org.slf4j.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.data.redis.core.StringRedisTemplate; import org.springframework.stereotype.Component;
@Component public class RedisMarketDataCache implements MarketDataCache {
 private static final Logger log=LoggerFactory.getLogger(RedisMarketDataCache.class); private final StringRedisTemplate redis; private final ObjectMapper json; private final Duration quoteTtl,candleTtl,intradayCandleTtl;
 public RedisMarketDataCache(StringRedisTemplate redis,ObjectMapper json,@Value("${trading.cache.quote-ttl-seconds:150}") long quote,@Value("${trading.cache.candle-ttl-seconds:3600}") long candles,@Value("${trading.cache.intraday-candle-ttl-seconds:300}") long intradayCandles){this.redis=redis;this.json=json;quoteTtl=Duration.ofSeconds(quote);candleTtl=Duration.ofSeconds(candles);intradayCandleTtl=Duration.ofSeconds(intradayCandles);}
 public Optional<Quote> getQuote(String key){return read("market:quote:"+key,Quote.class);} public void putQuote(String key,Quote value){write("market:quote:"+key,value,quoteTtl);}
 public Optional<List<Candle>> getCandles(String key,Timeframe t,String range){try{String raw=redis.opsForValue().get(candleKey(key,t,range));return raw==null?Optional.empty():Optional.of(json.readValue(raw,new TypeReference<List<Candle>>(){}));}catch(Exception e){warn(e);return Optional.empty();}}
 public void putCandles(String key,Timeframe t,String range,List<Candle> values){write(candleKey(key,t,range),values,"intraday".equals(range)?intradayCandleTtl:candleTtl);} public void evictQuote(String key){delete("market:quote:"+key);} public void evictCandles(String key,Timeframe t,String range){delete(candleKey(key,t,range));}
 private <T> Optional<T> read(String key,Class<T> type){try{String raw=redis.opsForValue().get(key);return raw==null?Optional.empty():Optional.of(json.readValue(raw,type));}catch(Exception e){warn(e);return Optional.empty();}} private void write(String key,Object value,Duration ttl){try{redis.opsForValue().set(key,json.writeValueAsString(value),ttl);}catch(Exception e){warn(e);}}private void delete(String key){try{redis.delete(key);}catch(Exception e){warn(e);}}private String candleKey(String key,Timeframe t,String range){return "market:candles:"+key+":"+t+":"+range;}private void warn(Exception e){log.warn("Redis cache unavailable; continuing without cache ({})",e.getClass().getSimpleName());}
}
